config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tasks', to: "tasks#index"
  get '/tasks/new', to: "tasks#new", as: :new_task
  get '/tasks/:id', to: "tasks#show", as: :task
  post '/tasks', to: "tasks#create"
  get '/tasks/:id/edit', to: "tasks#edit", as: :edit_task
  patch '/tasks/:id', to: "tasks#update"
  delete '/tasks/:id', to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path

  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div>
  <%= form_for(task) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
    <%= f.submit %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>All my tasks</h1>
<ul>
  <% @tasks.each do |task| %>
  <li>
    <div class="d-flex">
      <% if task.completed %>
      <i class="far fa-check-square"></i>
      <% else%>
      <i class="far fa-square"></i>
      <% end %>
      <h5 class="pl-2"><%= task.title %><h5>
    </div>
    <p><%= task.details %> </p>
    <%= link_to "back to Tasks", task_path(task) %>
  </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="d-flex mt-3">
<% if @task.completed %>
    <div class="mt-3 mr-2"> <i class="far fa-check-square"></i></div>
    <% else%>
    <div class="mt-3 mr-2"><i class="far fa-square"></i></div>
      <% end %>
<h1><%= @task.title %></h1>
</div>
<h2><%= @task.details %> </h2>
<%= link_to "back to Tasks", tasks_path %>
<br>
<%= link_to "edit task", edit_task_path(@task) %>
<br>
 <%= link_to 'destroy ', task_path(@task), method: :delete, data: {confirm: "Are you sure?"}%> <i class="fas fa-trash-alt"> </i>